Departments endpoint - also refactored createQueryFunc by adding include parameter
team120/University-projects-manager pull request #24
Opened 2021-03-09 17:49 UTC by JAcciarri

2021-03-09 18:57 UTC, alereca requested changes

2021-03-09 18:57 UTC, alereca commented on src/migrations/1590967789743-SeedDb.ts
> +      }),
Puede ser que estos jamas creen proyectos al ser departamentos administrativos y no académicos? Igual es para testing pero tal vez seria mejor agregar mas de los académicos

2021-03-09 18:57 UTC, alereca commented on src/utils/common/common.query.interface.ts
> +  include?: string[],
Acá para que sea mas explicito podríamos empezar a usar relationsToInclude ?

2021-03-09 18:57 UTC, alereca commented on e2e/database/migrations/1584749320190-SeedInMemoryTestDb.ts
> +      }),
Me refiero a esta parte tmb en el primer comentario

2021-03-09 19:24 UTC, JAcciarri commented on src/migrations/1590967789743-SeedDb.ts
> +      }),
Tenes razon, entre a la pagina de la facultad para ver ejemplos y los agregue de forma ciega. Tiene mas sentidos los otros deptos

2021-03-09 19:24 UTC, JAcciarri commented on src/utils/common/common.query.interface.ts
> +  include?: string[],
Si, es mas descriptivo ese nombre. Ahora lo cambio en los otros lugares

2021-03-09 19:35 UTC, JAcciarri commented
Changes made according to suggestions, please review

2021-03-09 21:41 UTC, alereca approved these changes

2021-03-10 02:42 UTC, NicoAntonelli approved these changes

2021-03-10 02:42 UTC, merged